#ifndef __PATH_TYPES
#define __PATH_TYPES

// All the relevant and possible options for a path to be during validation.
typedef enum
{
	VALID_PATH,
	INVALID_PATH_TO_EXISTING_FILE,
	INVALID_PATH_TO_EXISTING_DIR,
	INVALID_PATH_TO_DIR,
	INVALID_PATH_FILE_EXIST_BUT_ITS_A_DIR_PATH,
	INVALID_PATH_NAME,
	PATH_IS_EVIL,
	INVALID_CHARACTERS_IN_PATH,
	INCOMPLETE_UNC_PATH,
	INVALID_UNC_PATH,
	PATH_IS_AN_EXECUTABLE
} PATHS_T;

#endif //__PATH_TYPES